version: "3.8"

services:
  api:
    image: boxedition/cloud-api:latest
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - db
      - tunnel
    volumes:
      - api_data:/app
    command: sh -c "sed -i 's/DB_HOST=.*/DB_HOST=database/' .env &&sed -i 's/AWS_ACCESS_KEY_ID=.*/AWS_ACCESS_KEY_ID=database/' .env && php artisan serve --host=0.0.0.0 --port=8080"

  database:
    image: boxedition/cloud-db:latest
    ports:
      - "3306:3306"
    networks:
      - db
    volumes:
      - database_data:/var/lib/mysql

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    networks:
      - tunnel
    environment:
      TUNNEL_TOKEN: "${TUNNEL_TOKEN}"

networks:
  db:
  tunnel:

volumes:
  api_data:
  database_data:
