version: "3.8"

services:
  api:
    image: boxedition/cloud-api
    ports:
      - "80:8080"
    depends_on:
      - database
    networks:
      - db
      - tunnel
    volumes:
      - api_data:/app
    command: sh -c "sed -i 's/DB_HOST=.*/DB_HOST=database/' .env && tail -f /dev/null"

  database:
    image: boxedition/cloud-db
    ports:
      - "3306:3306"
    networks:
      - db
    volumes:
      - database_data:/var/lib/mysql

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    networks:
      - tunnel
    environment:
      TUNNEL_TOKEN: "${TUNNEL_TOKEN}"

networks:
  db:
  tunnel:

volumes:
  api_data:
  database_data:
