FROM php:8.1-fpm-alpine

#Extentions
RUN docker-php-ext-install pdo pdo_mysql
#Install composer
RUN curl -sS https://getcomposer.org/installer | php -- \
     --install-dir=/usr/local/bin --filename=composer

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /app
COPY . .
#Intallar dependencies
RUN composer install

CMD php artisan serve --host=0.0.0.0 --port=8080
EXPOSE 8080