services:
    database:
        build:
            context: .
            dockerfile: Dockerfile.database
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - db
    api:
        depends_on:
            - database
        build:
            context: .
            dockerfile: Dockerfile.api
        ports:
            - "8080:8080"
        networks:
            - db
        # Command to be executed inside the 'api' service container. It performs the following actions:
        #1. Replaces the value of 'DB_HOST' in the .env file with 'database'.
        #2. Generates a new application key using 'php artisan key:generate'.
        #3. Starts the application server using 'php artisan serve' with host set to '0.0.0.0' and port set to '8080'.
        #4. Executes database migrations and seeds using 'php artisan migrate:fresh --seed'.
        #5. Generates a new application key again.
        command: sh -c "sed -i 's/DB_HOST=.*/DB_HOST=database/' .env  && php artisan key:generate && sleep 5 && php artisan migrate:fresh --seed && php artisan serve --host=0.0.0.0 --port=8080 "

networks:
    db:

volumes:
    mysql:
