# Use the official MySQL image from Docker Hub
FROM mysql:latest

#Permitions of /var/lib/mysql/
RUN chown -R mysql /var/lib/mysql/

ARG MYSQL_DATABASE

ENV MYSQL_DATABASE=$MYSQL_DATABASE
ENV MYSQL_ALLOW_EMPTY_PASSWORD=1

# Define a volume mapping in the Dockerfile
VOLUME mysql:/var/lib/mysql

# Expose the MySQL port
EXPOSE 3306