version: "3"

services:
  ftp-server:
    image: fauria/vsftpd
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - ftp:/home/vsftpd
    environment:
      - FTP_USER=admin
      - FTP_PASS=secret
      - PASV_ADDRESS=127.0.0.1

  filezilla:
    image: jlesage/filezilla
    ports:
      - "5800:5800"
    volumes:
      - "filezilla:/config:rw"
    restart: always
    networks:
      - tunnel
    depends_on:
      - ftp-server
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    networks:
      - tunnel
    environment:
      TUNNEL_TOKEN: "${TUNNEL_TOKEN}"

volumes:
  ftp:
  filezilla:
